package com.huntkey.rx.sceo.monitor.commom.model;

import java.util.Date;

public class SysUserSecurity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.user_id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.result
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Boolean result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.old_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String oldValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.new_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String newValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.create_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_security.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.id
     *
     * @return the value of sys_user_security.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.id
     *
     * @param id the value for sys_user_security.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.user_id
     *
     * @return the value of sys_user_security.user_id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.user_id
     *
     * @param userId the value for sys_user_security.user_id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.type
     *
     * @return the value of sys_user_security.type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.type
     *
     * @param type the value for sys_user_security.type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.result
     *
     * @return the value of sys_user_security.result
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Boolean getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.result
     *
     * @param result the value for sys_user_security.result
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setResult(Boolean result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.old_value
     *
     * @return the value of sys_user_security.old_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getOldValue() {
        return oldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.old_value
     *
     * @param oldValue the value for sys_user_security.old_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setOldValue(String oldValue) {
        this.oldValue = oldValue == null ? null : oldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.new_value
     *
     * @return the value of sys_user_security.new_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getNewValue() {
        return newValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.new_value
     *
     * @param newValue the value for sys_user_security.new_value
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setNewValue(String newValue) {
        this.newValue = newValue == null ? null : newValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.create_time
     *
     * @return the value of sys_user_security.create_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.create_time
     *
     * @param createTime the value for sys_user_security.create_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_security.delete_flag
     *
     * @return the value of sys_user_security.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_security.delete_flag
     *
     * @param deleteFlag the value for sys_user_security.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}