package com.huntkey.rx.sceo.monitor.commom.model;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import org.hibernate.validator.constraints.NotEmpty;

import java.util.Date;

public class SysUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    @NotEmpty
    @Length(max = 16,min = 1)
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.world_post
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String worldPost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobile_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String mobileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.nationality
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    @Email
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.state
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.certificate_type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String certificateType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.certificate_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.name_real_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Boolean nameRealFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.question_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Boolean questionFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.register_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    private Boolean deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_name
     *
     * @return the value of sys_user.login_name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_name
     *
     * @param loginName the value for sys_user.login_name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.world_post
     *
     * @return the value of sys_user.world_post
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getWorldPost() {
        return worldPost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.world_post
     *
     * @param worldPost the value for sys_user.world_post
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setWorldPost(String worldPost) {
        this.worldPost = worldPost == null ? null : worldPost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobile_number
     *
     * @return the value of sys_user.mobile_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getMobileNumber() {
        return mobileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobile_number
     *
     * @param mobileNumber the value for sys_user.mobile_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber == null ? null : mobileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.nationality
     *
     * @return the value of sys_user.nationality
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.nationality
     *
     * @param nationality the value for sys_user.nationality
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name
     *
     * @return the value of sys_user.name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name
     *
     * @param name the value for sys_user.name
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.state
     *
     * @return the value of sys_user.state
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.state
     *
     * @param state the value for sys_user.state
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.certificate_type
     *
     * @return the value of sys_user.certificate_type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.certificate_type
     *
     * @param certificateType the value for sys_user.certificate_type
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.certificate_number
     *
     * @return the value of sys_user.certificate_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.certificate_number
     *
     * @param certificateNumber the value for sys_user.certificate_number
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.name_real_flag
     *
     * @return the value of sys_user.name_real_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Boolean getNameRealFlag() {
        return nameRealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.name_real_flag
     *
     * @param nameRealFlag the value for sys_user.name_real_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setNameRealFlag(Boolean nameRealFlag) {
        this.nameRealFlag = nameRealFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.question_flag
     *
     * @return the value of sys_user.question_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Boolean getQuestionFlag() {
        return questionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.question_flag
     *
     * @param questionFlag the value for sys_user.question_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setQuestionFlag(Boolean questionFlag) {
        this.questionFlag = questionFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.register_time
     *
     * @return the value of sys_user.register_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.register_time
     *
     * @param registerTime the value for sys_user.register_time
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.delete_flag
     *
     * @return the value of sys_user.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public Boolean getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.delete_flag
     *
     * @param deleteFlag the value for sys_user.delete_flag
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}