apiVersion: v1
kind: Service
metadata:
  name: biz-monitor-client-service
spec:
  type: NodePort
  ports:
    - port: 10041
      nodePort: 30041
      targetPort: 10041
      protocol: TCP
  selector:
    name: biz-monitor-client