package com.huntkey.rx.sceo.monitor.provider.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.huntkey.rx.sceo.monitor.commom.model.SysUserSecurity;
import com.huntkey.rx.sceo.monitor.commom.model.SysUserSecurityExample;

public interface SysUserSecurityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    long countByExample(SysUserSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int deleteByExample(SysUserSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int insert(SysUserSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int insertSelective(SysUserSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    List<SysUserSecurity> selectByExample(SysUserSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    SysUserSecurity selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int updateByExampleSelective(@Param("record") SysUserSecurity record, @Param("example") SysUserSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int updateByExample(@Param("record") SysUserSecurity record, @Param("example") SysUserSecurityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int updateByPrimaryKeySelective(SysUserSecurity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_security
     *
     * @mbg.generated Mon May 08 11:43:21 CST 2017
     */
    int updateByPrimaryKey(SysUserSecurity record);

    /**
     * 根据用户id和类型更新deleteFlag
     *
     * @param userId
     * @param type
     * @return
     */
    int updateDeleteFlagByUserIdAndType(@Param("deleteFlag") Boolean deleteFlag, @Param("userId") String userId, @Param("type") Integer type);

}