apiVersion: v1
kind: Service
metadata:
  name: biz-monitor-provider-service
spec:
  type: NodePort
  ports:
    - port: 10042
      nodePort: 30042
      targetPort: 10042
      protocol: TCP
  selector:
    name: demo-provider