spring:
  application:
    name: biz-monitor-provider
  messages:
    encoding: UTF-8
    basename: i18n/base
    fallback-to-system-locale: false
mybatis:
  mapperLocations: classpath:mapper/*.xml
redis:
  key:
    timeout: 24